services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sureify
      - DB_USER=mdkashif
      - DB_PASSWORD=mdkashif
      - JWT_SECRET=sureify@123

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sureify
      POSTGRES_USER: mdkashif
      POSTGRES_PASSWORD: mdkashif
    # if 5432 is still in use on your host, change to "5433:5432" here
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

